# Exported from Render on 2024-12-19T08:19:08Z
services:
- type: web
  name: clouad
  runtime: node
  repo: https://github.com/ISSOLAHmelissa/clouad
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  region: frankfurt
  buildCommand: npm install
  startCommand: npm start
version: "1"
